"""initial_schema

Revision ID: 12f44fc7694e
Revises: 
Create Date: 2026-09-18 10:05:02.511945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f44fc7694e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reg_number', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'SUSPENDED', name='companyapprovalstatus'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('suspend_reason', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('JOB_POSTING', 'COMPANY_REGISTRATION', name='moderationtype'), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('flagged_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACTIONED', 'DISMISSED', name='moderationstatus'), nullable=False),
    sa.Column('target_data', sa.JSON(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=100), nullable=False),
    sa.Column('posting_limit', sa.Integer(), nullable=True),
    sa.Column('retention_months', sa.Integer(), nullable=False),
    sa.Column('ai_features', sa.Boolean(), nullable=False),
    sa.Column('blurb', sa.String(length=255), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'COMPANY_HR', 'COMPANY_VIEWER', 'JOB_SEEKER', name='userrole'), nullable=False),
    sa.Column('invite_token', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_invitations_invite_token'), ['invite_token'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'COMPANY_HR', 'COMPANY_VIEWER', 'JOB_SEEKER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('salary_min', sa.String(length=50), nullable=True),
    sa.Column('salary_max', sa.String(length=50), nullable=True),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('jd', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience', sa.String(length=50), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'PAUSED', 'CLOSED', name='jobstatus'), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('APPLICATION', 'INTERVIEW', 'STATUS', 'OFFER', 'QUOTA', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('seeker_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('resume_file_name', sa.String(length=255), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('resume_size', sa.Integer(), nullable=True),
    sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('privacy_settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('seeker_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'OFFER_SENT', 'HIRED', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('resume_file_name', sa.String(length=255), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('rejection_template_id', sa.String(length=50), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_seeker_id'), ['seeker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_stage'), ['stage'], unique=False)

    op.create_table('saved_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_jobs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('application_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_notes_application_id'), ['application_id'], unique=False)

    op.create_table('application_timelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'OFFER_SENT', 'HIRED', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_timelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_timelines_application_id'), ['application_id'], unique=False)

    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('round_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('VIDEO', 'IN_PERSON', 'PHONE', name='interviewmode'), nullable=False),
    sa.Column('location_or_link', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('interviewers', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'CONFIRMED', 'DECLINED', 'COMPLETED', 'CANCELLED', name='interviewstatus'), nullable=False),
    sa.Column('response_note', sa.Text(), nullable=True),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_application_id'), ['application_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_application_id'))

    op.drop_table('interviews')
    with op.batch_alter_table('application_timelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_timelines_application_id'))

    op.drop_table('application_timelines')
    with op.batch_alter_table('application_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_notes_application_id'))

    op.drop_table('application_notes')
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_jobs_job_id'))

    op.drop_table('saved_jobs')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_stage'))
        batch_op.drop_index(batch_op.f('ix_applications_seeker_id'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    op.drop_table('seeker_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('company_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_invitations_invite_token'))

    op.drop_table('company_invitations')
    op.drop_table('subscription_plans')
    op.drop_table('moderation_items')
    op.drop_table('companies')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
