"""add_seeker_resume_table_and_photo_columns

Revision ID: f92a464fa6bc
Revises: fa5d0524fe54
Create Date: 2026-09-18 11:46:34.410967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92a464fa6bc'
down_revision: Union[str, Sequence[str], None] = 'fa5d0524fe54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seeker_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_data_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('photo_mime_type', sa.String(length=100), nullable=True))
        batch_op.drop_column('resume_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seeker_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_mime_type')
        batch_op.drop_column('photo_data_url')
        batch_op.drop_column('resume_mime_type')

    # ### end Alembic commands ###
