"""add_is_active_and_is_deleted_to_all_tables

Revision ID: fa5d0524fe54
Revises: 12f44fc7694e
Create Date: 2026-09-18 10:22:02.157270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5d0524fe54'
down_revision: Union[str, Sequence[str], None] = '12f44fc7694e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('application_timelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('company_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('moderation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('seeker_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('seeker_profiles', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('moderation_items', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('company_invitations', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('application_timelines', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('application_notes', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
