from shared.schemas.common import BaseResponse, APIResponse, PaginationMeta, PaginatedResponse
from shared.schemas.auth import (
    LoginRequest,
    RegisterRequest,
    TokenResponse,
    RefreshTokenRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    SendVerificationEmailRequest,
    VerifyEmailRequest,
    ChangePasswordRequest,
)
from shared.schemas.role import (
    PermissionBase,
    PermissionCreate,
    PermissionOut,
    RoleBase,
    RoleCreate,
    RoleUpdate,
    RoleOut,
)
from shared.schemas.user import UserBase, UserCreate, UserUpdate, UserOut
from shared.schemas.company import (
    CompanyProfileBase,
    CompanyProfileCreate,
    CompanyProfileUpdate,
    CompanyProfileOut,
    CompanyVerifyRequest,
)
from shared.schemas.jobseeker import (
    JobSeekerProfileBase,
    JobSeekerProfileCreate,
    JobSeekerProfileUpdate,
    JobSeekerProfileOut,
    SavedJobOut,
)
from shared.schemas.job import (
    JobPostingBase,
    JobPostingCreate,
    JobPostingUpdate,
    JobPostingOut,
    JobFilterParams,
)
from shared.schemas.application import (
    ApplicationCreate,
    ApplicationStatusUpdate,
    ApplicationOut,
)

__all__ = [
    "BaseResponse",
    "APIResponse",
    "PaginationMeta",
    "PaginatedResponse",
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "SendVerificationEmailRequest",
    "VerifyEmailRequest",
    "ChangePasswordRequest",
    "PermissionBase",
    "PermissionCreate",
    "PermissionOut",
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RoleOut",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserOut",
    "CompanyProfileBase",
    "CompanyProfileCreate",
    "CompanyProfileUpdate",
    "CompanyProfileOut",
    "CompanyVerifyRequest",
    "JobSeekerProfileBase",
    "JobSeekerProfileCreate",
    "JobSeekerProfileUpdate",
    "JobSeekerProfileOut",
    "SavedJobOut",
    "JobPostingBase",
    "JobPostingCreate",
    "JobPostingUpdate",
    "JobPostingOut",
    "JobFilterParams",
    "ApplicationCreate",
    "ApplicationStatusUpdate",
    "ApplicationOut",
]
